title: ANTIBODY
license: HL3-BDS-MEDIA-SUP-SV
license_extra: You may copy from this code, text and license, only if you attribute yourself as the author.
license_badge: https://img.shields.io/static/v1?label=Hippocratic%20License&message=HL3-BDS-MEDIA-SUP-SV&labelColor=5e2751&color=2a6a65
license_url: https://firstdonoharm.dev/version/3/0/bds-media-sup-sv.html
civic_node: Fort Collins
civic_abbr: FCCN
civic_tag: For immediate replication
civic_readme: |
  [# README](/README)

  This is [an open-source publication](https://github.com/tiliv/antibody) of
  local-made journalism.

  News media will waste our time; Their nutrition is secured through our
  attention, and our data. They have had it all, but cannot hear us.

  We assert that there are degrees of information quality, that we must not
  struggle to distinguish them and that they are these: 1) First-party claims
  with metadata, 2) Hearsay and 3) Fraud.

  It is necessary for our social cohesion that we possess various ways and
  means of direct information exchange within our cities. Our Domestic Enemies
  have taken our placation as given, however We the People have acquired on our
  own several talents and skills to deploy in our defense.
civic_license: |
  [# LICENSE](/LICENSE)

  This license is to be obeyed. It may change at any time because we
  don't have to notify whoever or whatever you are.

  This document constitutes your First Warning.

  These authors' words and derivatives cannot be sold except by
  Their Own Human Authority:

  1. Autumn Ryan

  If you republish their words in compliance with the larger installation
  license, you must adopt them as your words signed by your name:

  You Are Allowed to rebroadcast what we say, If You Say It Too.

preferences:
  dark: false

# Jekyll options
theme: null
permalink: pretty
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  gfm_quirks: paragraph_end
  template: ""
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: plaintext
sass:
  style: compressed

defaults:
  - scope: {path: ""}
    values:
      preferences: journal
  - scope: {path: "journal"}
    values:
      layout: journal
exclude:
  - CNAME
  - .bundle
  - Gemfile
  - Gemfile.lock
  - vendor

plugins:
  - jekyll-link-attributes
  - jekyll-redirect-from
